// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeHCiqHy2h9S3ShSJP05OyjuRtrOtyyqc',
    appId: '1:45007901841:web:0e931de9cdb5a9ea061b30',
    messagingSenderId: '45007901841',
    projectId: 'bucketlistwithfirebase-8b5ae',
    authDomain: 'bucketlistwithfirebase-8b5ae.firebaseapp.com',
    storageBucket: 'bucketlistwithfirebase-8b5ae.appspot.com',
    measurementId: 'G-K0HS8261F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW2hnnn7yJhju4R0Ba__gd-XcdlBlPz20',
    appId: '1:45007901841:android:bcc81c932ab18bab061b30',
    messagingSenderId: '45007901841',
    projectId: 'bucketlistwithfirebase-8b5ae',
    storageBucket: 'bucketlistwithfirebase-8b5ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9MG0ci0QZtD1Hbf7m6VkgjS8HisakK-w',
    appId: '1:45007901841:ios:0ba29cb9dcfbaa2a061b30',
    messagingSenderId: '45007901841',
    projectId: 'bucketlistwithfirebase-8b5ae',
    storageBucket: 'bucketlistwithfirebase-8b5ae.appspot.com',
    iosClientId: '45007901841-8fb65lsdj3kqumbe2t796kg8hrgqf1d5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bucketListWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9MG0ci0QZtD1Hbf7m6VkgjS8HisakK-w',
    appId: '1:45007901841:ios:0ba29cb9dcfbaa2a061b30',
    messagingSenderId: '45007901841',
    projectId: 'bucketlistwithfirebase-8b5ae',
    storageBucket: 'bucketlistwithfirebase-8b5ae.appspot.com',
    iosClientId: '45007901841-8fb65lsdj3kqumbe2t796kg8hrgqf1d5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bucketListWithFirebase',
  );
}
