// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1HC5lkoerc4cyFjC69Aa84lVIgN1fpfU',
    appId: '1:126181310389:web:652bdb47507c2bb7c863fc',
    messagingSenderId: '126181310389',
    projectId: 'teacherhelper-eebba',
    authDomain: 'teacherhelper-eebba.firebaseapp.com',
    storageBucket: 'teacherhelper-eebba.appspot.com',
    measurementId: 'G-0GR152KB3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeMOHv6yN5YB3Qk0HqfBlKT3RSl3P18h8',
    appId: '1:126181310389:android:19092676ca767cdec863fc',
    messagingSenderId: '126181310389',
    projectId: 'teacherhelper-eebba',
    storageBucket: 'teacherhelper-eebba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWt9m9iyancXamqMX4itbnb2UlNHGsp_w',
    appId: '1:126181310389:ios:b3e64e7c5b057abec863fc',
    messagingSenderId: '126181310389',
    projectId: 'teacherhelper-eebba',
    storageBucket: 'teacherhelper-eebba.appspot.com',
    iosBundleId: 'com.example.teacherhelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWt9m9iyancXamqMX4itbnb2UlNHGsp_w',
    appId: '1:126181310389:ios:b3e64e7c5b057abec863fc',
    messagingSenderId: '126181310389',
    projectId: 'teacherhelper-eebba',
    storageBucket: 'teacherhelper-eebba.appspot.com',
    iosBundleId: 'com.example.teacherhelper',
  );
}
